export const patchSystemAppDictRu = () => {
  Localization_systemAppDict_ru_RU['SensorsApp'] = 'Показания датчиков'
  Localization_systemAppDict_ru_RU['SensorsErrorTitle'] = 'Ошибка'
  Localization_systemAppDict_ru_RU['SensorsErrorBack'] = 'Назад'
  Localization_systemAppDict_ru_RU['SensorsPCMVoltage'] = 'Напряжение на PCM'
  Localization_systemAppDict_ru_RU['SensorsPCMVoltageValue'] = '{value} в'
  Localization_systemAppDict_ru_RU['SensorsOilLevel'] = 'Уровень масла'
  Localization_systemAppDict_ru_RU['SensorsOilLevelValue'] = '{value} мм'
  Localization_systemAppDict_ru_RU['SensorsOilTemp'] = 'Температура масла'
  Localization_systemAppDict_ru_RU['SensorsOilTempValue'] = '{value} °C'
  Localization_systemAppDict_ru_RU['SensorsOilPress'] = 'Давление масла'
  Localization_systemAppDict_ru_RU['SensorsOilPressValue'] = '{value} кПа'
  Localization_systemAppDict_ru_RU['SensorsTirePress1'] = 'Давление в колесе 1'
  Localization_systemAppDict_ru_RU['SensorsTirePress2'] = 'Давление в колесе 2'
  Localization_systemAppDict_ru_RU['SensorsTirePress3'] = 'Давление в колесе 3'
  Localization_systemAppDict_ru_RU['SensorsTirePress4'] = 'Давление в колесе 4'
  Localization_systemAppDict_ru_RU['SensorsTirePressValue'] = '{value} кПа'
}
